"""empty message

Revision ID: b80ebbbc51dc
Revises: 
Create Date: 2022-09-12 12:17:22.001938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b80ebbbc51dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('qqId', sa.String(length=20), nullable=False),
    sa.Column('isDetect', sa.BOOLEAN(), nullable=True),
    sa.Column('auth', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_qqId'), 'group', ['qqId'], unique=True)
    op.create_table('groupAuth',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chat', sa.INTEGER(), nullable=False),
    sa.Column('welcome', sa.INTEGER(), nullable=False),
    sa.Column('banTalk', sa.INTEGER(), nullable=True),
    sa.Column('click', sa.INTEGER(), nullable=True),
    sa.Column('smallFunction', sa.INTEGER(), nullable=True),
    sa.Column('dailyBrief', sa.INTEGER(), nullable=True),
    sa.Column('groupId', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['groupId'], ['group.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('groupAuth')
    op.drop_index(op.f('ix_group_qqId'), table_name='group')
    op.drop_table('group')
    # ### end Alembic commands ###
