"""empty message

Revision ID: c26358e6bf5e
Revises: 3ff8e991221b
Create Date: 2022-09-17 07:34:03.486279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c26358e6bf5e'
down_revision = '3ff8e991221b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('groupAuth_ibfk_1', 'groupAuth', type_='foreignkey')
    op.create_foreign_key(None, 'groupAuth', 'group', ['groupId'], ['id'], ondelete='DELETE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groupAuth', type_='foreignkey')
    op.create_foreign_key('groupAuth_ibfk_1', 'groupAuth', 'group', ['groupId'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
